### ISSUE TITLE
Library does not support unsubscribe method

### ISSUE THREAD

**Issue by ckeeney** [outboundio/lib-python#3]
The library does not have any support unsubscribing from campaigns.  
http://docs.outbound.io/docs/unsubscribe-all-campaigns  

http://docs.outbound.io/docs/unsubscribe-single-campaign

**Comment by MrTravisB** [comment]
Sorry @ckeeney for not updating you sooner. Not sure if you're aware but we pushed out these methods in the Python library.

**Comment by ckeeney** [comment]
Thanks.  looks good and I will check it out.
